- name: 渲染 Node 配置文件
  template:
    src: '{{ item }}'
    dest: '{{ install_dir }}/kubernetes/conf/'
  with_fileglob: 'templates/node/conf/*'

- name: 渲染 Node 相关 Service unit 文件
  template:
    src: '{{ item }}'
    dest: '{% if ansible_distribution == "CentOS" %}/usr{% endif %}/lib/systemd/system/'
  with_fileglob: 'templates/node/systemd/*'
