- set_fact:
    etcd_package_name: etcd-v*-linux-amd64
    kubernetes_package_name: kubernetes
    docker_package_name: docker*
    cni_package_name: cni-plugins-linux-amd64-*
  tags:
  - send_etcd
  - send_kubernetes
  - send_docker
  - send_cni
  - clear_package

- import_tasks: send_etcd.yml
  when: etcd is defined and etcd
  tags:
  - send_etcd

- import_tasks: send_kubernetes.yml
  when: (master is defined and master) or (node is defined and node)
  tags:
  - send_kubernetes

- import_tasks: send_docker.yml
  when: (node is defined and node) or (is_mutil_master and proxy_master is defined and proxy_master)
  tags:
  - send_docker

- import_tasks: send_cni.yml
  when: node is defined and node
  tags:
  - send_cni

- import_tasks: clear_package.yml
  tags:
  - clear_package