- name: 检查是否 ETCD 二进制包是否已存在
  become: yes
  ignore_errors: yes
  changed_when: no
  failed_when: no
  shell: '[ -f /opt/apps/etcd/bin/etcd ] && [ -f /opt/apps/etcd/bin/etcdctl ]'
  register: check_result
- block:
  - name: 解压 ETCD 安装包
    become: yes
    unarchive:
      src: '{{ item }}'
      dest: /tmp
    with_fileglob: '{{ package_dir }}/{{ etcd_package_name }}.tar.gz'

  - name: 移动可执行文件到 /opt/apps/etcd/bin
    become: yes
    shell: mv /tmp/{{ etcd_package_name }}/{etcd,etcdctl} /opt/apps/etcd/bin
  when: check_result.rc != 0