- name: 解压 cni 安装包到安装目录
  unarchive:
    src: '{{ item }}'
    dest: '{{ install_dir }}/cni/bin/'
  with_fileglob: '{{ package_dir }}/{{ cni_package_name }}.tgz'
  when: cni_type is defined and cni_type == 'flannel'
