all:
  vars:
    ansible_user: root
    ansible_ssh_pass: root1234
    ansible_sudo_pass: root1234
    # 是否是多 Master 架构
    is_mutil_master: no
    # 多主架构时使用，Keepalived VIP
    virtual_ip: 10.0.1.200
    # 多主架构时 Nginx 代理 apiserver 使用的端口，如果代理和 apiserver 在同一台主机则不能和 apiserver 的 6443 端口冲突
    ha_proxy_port: 7443
    # 安装目录
    install_dir: /opt/apps/
    # 用到的二进制包目录
    package_dir: /opt/packages/
    # 本地证书存放目录，要求当前运行 Ansible 的用户拥有该目录的写权限，否则证书无法生成（或者使用 sudo 执行 ansible-playbook）
    tls_dir: /opt/k8s_tls
    # 提供 NTP 时间同步服务的主机，将会添加到定时任务
    ntp_host: ntp1.aliyun.com
    # 是否可以连接到 internet，如果可以，则会自动装 ntpdate 等工具
    have_network: yes
    # 是否修改 yum 源或 apt 源为阿里云，支持 CentOS 7、Ubuntu 16、Ubuntu 18，注意，会清空原有的源配置
    replace_repo: yes
    # API Server 证书预留 IP 列表，默认：
    # - 单 master 情况下只会添加 master 节点 IP
    # - 多 master 情况下会添加 master 节点 IP 和 ha_proxy 节点 IP
    api_server_ext_ip_list:
    - 10.0.1.210
    - 10.0.1.211
    - 10.0.1.212
    # 可信任的 Docker 镜像仓库地址，默认仅允许 HTTPS 仓库，添加后可支持 HTTP，用于渲染 /opt/apps/docker/conf/daemon.json
    docker_insecure_registries:
    - 10.0.1.122
    - 10.0.1.123
    # Docker 仓库地址，可选，注释后默认为我的阿里云镜像加速地址
    docker_registry_mirrors: https://7hsct51i.mirror.aliyuncs.com
    # kubelet 用来发送签发证书请求用的 Token，可通过 head -c 16 /dev/urandom | od -An -t x | tr -d ' ' 生成
    kubelet_bootstrap_token: 8fba966b6e3b5d182960a30f6cb94428
    # pause 镜像
    pause_image: registry.cn-shenzhen.aliyuncs.com/zze/pause:3.2
  hosts:
    10.0.1.201:
      hostname: k8s-master
      master: yes
      etcd: yes
    10.0.1.202:
      hostname: k8s-node1
      node: yes
      etcd: yes
      ha_proxy: yes
    10.0.1.203: 
      hostname: k8s-node2
      node: yes
      ha_proxy: yes
