- name: 安装 ntpdate
  apt:
    name: 
    - ntpdate
    - bash-completion
  when: have_network

- name: 替换 apt 源为阿里云
  copy:
    src: 'ubuntu{{ ansible_distribution_major_version }}-repo/sources.list'
    dest: /etc/apt/sources.list
  when: have_network and replace_repo

- name: 关闭 Swap - swap off -a (1/2)
  shell: |
    /sbin/swapoff -a

- name: 关闭 Swap - /etc/fstab (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\sswap\s+\s+.*)$'
    replace: '# \1'

- name: 为 Ubuntu 18 创建 /etc/rc.local
  file:
    path: /etc/rc.local
    state: touch
    mode: '0755'
  when: ansible_distribution_major_version == '18'