- name: 安装 ntpdate
  apt:
    name: 
    - ntpdate
    - bash-completion
  when: have_network

- name: 替换 apt 源为阿里云
  copy:
    src: 'ubuntu{{ ansible_distribution_major_version }}-repo/sources.list'
    dest: /etc/apt/sources.list
  when: have_network and replace_repo

- name: 关闭 Swap - swap off -a (1/2)
  shell: |
    /sbin/swapoff -a

- name: 关闭 Swap - /etc/fstab (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\sswap\s+\s+.*)$'
    replace: '# \1'

- name: 加载 IPVS 模块 - 修改 /etc/rc.local (1/2)
  lineinfile:
    line: 'for i in $(ls /usr/lib/modules/$(uname -r)/kernel/net/netfilter/ipvs|grep -o "^[^.]*");do /sbin/modinfo -F filename $i >/dev/null 2>&1 && /sbin/modprobe $i;done' 
    path: /etc/rc.local
    mode: '0755'

- name: 加载 IPVS 模块 - 立即加载 (2/2)
  changed_when: no
  shell: . /etc/rc.local