- name: 检查是否存在 ingress-controller manifests - manifests/haproxy-ingress-controller.yaml
  failed_when: no
  changed_when: no
  run_once: yes
  connection: local
  shell: 'ls {{ manifests_dir }}/{{ ingress_controller_type }}*ingress-controller*.yml {{ manifests_dir }}/{{ ingress_controller_type }}*ingress-controller*.yaml'
  register: check_ingress_result

- name: 设置变量
  run_once: yes
  set_fact:
    ingress_manifests_list: '{{ check_ingress_result.stdout_lines }}'

- block:
  - name: 为指定的 Ingress 节点打上标签
    become: yes
    failed_when: no
    shell: |
      kubectl get node -l 'ingress=yes' | awk 'NR>1 && $1=="{{ item }}"{print $1}' | grep '{{ item }}' \
        || kubectl label node {{ item }} ingress='yes'
    with_items: '{{ ingress_list }}'

  - name: 分发 ingress-controller manifests 到 master 节点
    template:
      src: '{{ item }}'
      dest: /tmp/
    with_items: '{{ ingress_manifests_list }}'

  - name: 部署 ingress-controller
    shell: kubectl apply -f /tmp/{{ item | basename }}
    with_items: '{{ ingress_manifests_list }}'
  when: ingress_manifests_list and ansible_host == master_list[0]

